//
// Created by rvmosq on 10/13/20.
//

#ifndef GG_PSQL_BD2_TESTEXTENDIBLE_H
#define GG_PSQL_BD2_TESTEXTENDIBLE_H

#include "../Components/ExtendibleHashing/Extendible.h"
#include "../Components/ExtendibleHashing/Juego.h"

class TestExtendible {
public:
    void static loadAll(string filename, string indexfile) {
        ExtendibleHash extend_table(filename, indexfile);

        extend_table.add(Juego("10","Counter-Strike","Valve",317));
        extend_table.add(Juego("20","Team Fortress C","Valve",62));
        extend_table.add(Juego("30","Day of Defeat","Valve",34));
        extend_table.add(Juego("40","Deathmatch Clas","Valve",184));
        extend_table.add(Juego("50","Half-Life: Oppo","Gearbox Software",415));
        extend_table.add(Juego("60","Ricochet","Valve",10));
        extend_table.add(Juego("70","Half-Life","Valve",83));
        extend_table.add(Juego("80","Counter-Strike:","Valve",43));
        extend_table.add(Juego("130","Half-Life: Blue","Gearbox Software",205));
        extend_table.add(Juego("220","Half-Life 2","Valve",402));
        extend_table.add(Juego("240","Counter-Strike:","Valve",400));
        extend_table.add(Juego("280","Half-Life: Sour","Valve",214));
        extend_table.add(Juego("300","Day of Defeat: ","Valve",134));
        extend_table.add(Juego("320","Half-Life 2: De","Valve",32));
        extend_table.add(Juego("340","Half-Life 2: Lo","Valve",29));
        extend_table.add(Juego("360","Half-Life Death","Valve",81));
        extend_table.add(Juego("380","Half-Life 2: Ep","Valve",184));
        extend_table.add(Juego("400","Portal","Valve",137));
        extend_table.add(Juego("420","Half-Life 2: Ep","Valve",301));
        extend_table.add(Juego("440","Team Fortress 2","Valve",623));
        extend_table.add(Juego("500","Left 4 Dead","Valve",278));
        extend_table.add(Juego("550","Left 4 Dead 2","Valve",566));
        extend_table.add(Juego("570","Dota 2","Valve",801));
        extend_table.add(Juego("620","Portal 2","Valve",520));
        extend_table.add(Juego("630","Alien Swarm","Valve",83));
        extend_table.add(Juego("730","Counter-Strike:","Valve;Hidden Path Entertainment",6502));
        extend_table.add(Juego("1002","Rag Doll Kung F","Mark Healey",0));
        extend_table.add(Juego("1200","Red Orchestra: ","Tripwire Interactive",258));
        extend_table.add(Juego("1250","Killing Floor","Tripwire Interactive",306));
        extend_table.add(Juego("1300","SiN Episodes: E","Ritual Entertainment",0));
        extend_table.add(Juego("1500","Darwinia","Introversion Software",273));
        extend_table.add(Juego("1510","Uplink","Introversion Software",77));
        extend_table.add(Juego("1520","DEFCON","Introversion Software",119));
        extend_table.add(Juego("1530","Multiwinia","Introversion Software",224));
        extend_table.add(Juego("1600","Dangerous Water","Sonalysts",0));
        extend_table.add(Juego("1610","Space Empires I","Malfador Machinations",0));
        extend_table.add(Juego("1630","Disciples II: R","Strategy First",0));
        extend_table.add(Juego("1640","Disciples II: G","Strategy First",12));
        extend_table.add(Juego("1670","Iron Warriors: ","Strategy First",0));
        extend_table.add(Juego("1690","Space Empires V","Malfador Machinations",35));
        extend_table.add(Juego("1700","Arx Fatalis","Arkane Studios",21));
        extend_table.add(Juego("1840","Source Filmmake","Valve",77));
        extend_table.add(Juego("1900","Earth 2160","Reality Pump Studios",414));
        extend_table.add(Juego("1930","Two Worlds Epic","Reality Pump Studios",422));
        extend_table.add(Juego("2100","Dark Messiah of","Arkane Studios",700));
        extend_table.add(Juego("2200","Quake III Arena","id Software",103));
        extend_table.add(Juego("2210","Quake IV","RavenSoft / id Software",32));
        extend_table.add(Juego("2270","Wolfenstein 3D","id Software",110));
        extend_table.add(Juego("2280","Ultimate Doom","id Software",179));
        extend_table.add(Juego("2290","Final DOOM","id Software",114));
        extend_table.add(Juego("2300","DOOM II","id Software",78));
        extend_table.add(Juego("2310","QUAKE","id Software",189));
        extend_table.add(Juego("2320","QUAKE II","id Software",349));
        extend_table.add(Juego("2330","QUAKE II Missio","Xatrix Entertainment",32));
        extend_table.add(Juego("2340","QUAKE II Missio","Rogue Entertainment",1));
        extend_table.add(Juego("2350","QUAKE III: Team","id Software",0));
        extend_table.add(Juego("2360","HeXen: Beyond H","Raven Software",50));
        extend_table.add(Juego("2370","HeXen: Deathkin","Raven Software",0));
        extend_table.add(Juego("2390","Heretic: Shadow","Raven Software",0));
        extend_table.add(Juego("2400","The Ship: Murde","Outerlight Ltd.",239));
        extend_table.add(Juego("2450","Bloody Good Tim","Outerlight Ltd.",193));
        extend_table.add(Juego("2500","Shadowgrounds","Frozenbyte",258));
        extend_table.add(Juego("2520","Gumboy - Crazy ","CINEMAX, s.r.o.",0));
        extend_table.add(Juego("2590","Alpha Prime","Black Element",0));
        extend_table.add(Juego("2600","Vampire: The Ma","Troika Games",202));
        extend_table.add(Juego("2610","GUN","Neversoft",889));
        extend_table.add(Juego("2620","Call of Duty","Infinity Ward",849));
        extend_table.add(Juego("2630","Call of Duty 2","Infinity Ward;Aspyr (Mac)",1041));
        extend_table.add(Juego("2640","Call of Duty: U","Gray Matter Studios",0));
        extend_table.add(Juego("2710","Act of War: Dir","Eugen Systems",0));
        extend_table.add(Juego("2720","ThreadSpace: Hy","Iocaine Studios",0));
        extend_table.add(Juego("2780","ARMA: Combat Op","Bohemia Interactive",0));
        extend_table.add(Juego("2800","X2: The Threat","Egosoft",732));
        extend_table.add(Juego("2810","X3: Reunion","Egosoft",1232));
        extend_table.add(Juego("2820","X3: Terran Conf","Egosoft",1273));
        extend_table.add(Juego("2840","X: Beyond the F","Egosoft",648));
        extend_table.add(Juego("2850","X: Tension","Egosoft",13));
        extend_table.add(Juego("2870","X Rebirth","Egosoft",3386));
        extend_table.add(Juego("2900","688(I) Hunter/K","Sonalysts",0));
        extend_table.add(Juego("2910","Fleet Command","Sonalysts",0));
        extend_table.add(Juego("2920","Sub Command","Sonalysts",0));
        extend_table.add(Juego("2990","FlatOut 2","Bugbear Entertainment",351));
        extend_table.add(Juego("3010","Xpand Rally","Techland",939));
        extend_table.add(Juego("3020","Call of Juarez","Techland",60));
        extend_table.add(Juego("3050","Xpand Rally Xtr","Techland",0));
        extend_table.add(Juego("3130","Men of War: Red","1C Entertainment",0));
        extend_table.add(Juego("3170","King's Bounty: ","Katauri Interactive",1429));
        extend_table.add(Juego("3230","Genesis Rising","Metamorf",0));
        extend_table.add(Juego("3260","Safecracker: Th","Kheops Studio",1));
        extend_table.add(Juego("3270","Painkiller Over","Mindware Studios",270));
        extend_table.add(Juego("3330","Zuma Deluxe","PopCap Games, Inc.",267));
        extend_table.add(Juego("3410","Heavy Weapon De","PopCap Games, Inc.",0));
        extend_table.add(Juego("3480","Peggle Deluxe","PopCap Games, Inc.",254));
        extend_table.add(Juego("3483","Peggle Extreme","PopCap Games, Inc.",1));
        extend_table.add(Juego("3490","Venice Deluxe","Retro64, Inc.",0));
        extend_table.add(Juego("3500","Mystery P.I. - ","SpinTop Games",0));
        extend_table.add(Juego("3510","Amazing Adventu","SpinTop Games",0));
        extend_table.add(Juego("3520","Mystery P.I. - ","SpinTop Games",0));
        extend_table.add(Juego("3530","Amazing Adventu","SpinTop Games",0));
        extend_table.add(Juego("3540","Peggle Nights","PopCap Games, Inc.",237));
        extend_table.add(Juego("3560","Bejeweled Twist","PopCap Games, Inc.",0));
        extend_table.add(Juego("3570","Mystery P.I. - ","SpinTop Games",0));
        extend_table.add(Juego("3580","The Wizard's Pe","PopCap Games, Inc.",0));
        extend_table.add(Juego("3590","Plants vs. Zomb","PopCap Games, Inc.",374));
        extend_table.add(Juego("3600","Escape Roseclif","SpinTop Games",0));
        extend_table.add(Juego("3610","Mystery P.I. - ","SpinTop Games",0));
        extend_table.add(Juego("3620","Zuma's Revenge!","PopCap Games, Inc.",0));
        extend_table.add(Juego("3700","Sniper Elite","Rebellion",371));
        extend_table.add(Juego("3710","Judge Dredd: Dr","Rebellion",8));
        extend_table.add(Juego("3720","Evil Genius","Elixir Studios",318));
        extend_table.add(Juego("3730","Aliens versus P","Rebellion",24));
        extend_table.add(Juego("3800","Advent Rising","GlyphX Games",0));
        extend_table.add(Juego("3810","BloodRayne","Terminal Reality",111));
        extend_table.add(Juego("3820","BloodRayne 2","Terminal Reality",771));
        extend_table.add(Juego("3830","Psychonauts","Double Fine Productions",232));
        extend_table.add(Juego("3900","Sid Meier's Civ","Firaxis Games",64));
        extend_table.add(Juego("3910","Sid Meier's Civ","Firaxis Games",13));
        extend_table.add(Juego("3920","Sid Meier's Pir","Firaxis Games",436));
        extend_table.add(Juego("3960","Shattered Union","PopTop",0));
        extend_table.add(Juego("3980","CivCity: Rome","FireFly Studios;Firaxis Games",0));
        extend_table.add(Juego("3990","Civilization IV","Firaxis Games",0));
        extend_table.add(Juego("4000","Garry's Mod","Facepunch Studios",1875));
        extend_table.add(Juego("4100","Poker Superstar","Funkitron",0));
        extend_table.add(Juego("4230","RACE - The WTCC","SimBin",0));
        extend_table.add(Juego("4290","RACE: Caterham ","SimBin",0));
        extend_table.add(Juego("4300","RoboBlitz","Naked Sky Entertainment",78));
        extend_table.add(Juego("4420","Silverfall","Monte Cristo",0));
        extend_table.add(Juego("4460","City Life 2008","Monte Cristo",0));
        extend_table.add(Juego("4470","Silverfall: Ear","Monte Cristo",0));
        extend_table.add(Juego("4500","S.T.A.L.K.E.R.:","GSC Game World",360));
        extend_table.add(Juego("4520","Full Spectrum W","Pandemic Studios",244));
        extend_table.add(Juego("4530","Full Spectrum W","Pandemic Studios",1));
        extend_table.add(Juego("4560","Company of Hero","Relic Entertainment",186));
        extend_table.add(Juego("4570","Warhammer 40,00","Relic Entertainment",340));
        extend_table.add(Juego("4580","Warhammer 40,00","Relic Entertainment",620));
        extend_table.add(Juego("4700","Total War: MEDI","CREATIVE ASSEMBLY;Feral Interactive (Mac);Feral Interactive (Linux)",361));
        extend_table.add(Juego("4720","Condemned: Crim","Monolith",312));
        extend_table.add(Juego("4760","Rome: Total War","CREATIVE ASSEMBLY",1192));
        extend_table.add(Juego("4770","Rome: Total War","The Creative Assembly",33));
        extend_table.add(Juego("4780","Medieval II: To","The Creative Assembly;Feral Interactive (Mac);Feral Interactive (Linux)",0));
        extend_table.add(Juego("4800","Heroes of Annih","GSC Game World",0));
        extend_table.add(Juego("4850","Cossacks: Back ","GSC Game World",1208));
        extend_table.add(Juego("4870","Cossacks: Art o","GSC Game World",0));
        extend_table.add(Juego("4880","Cossacks: Europ","GSC Game World",1));
        extend_table.add(Juego("4890","Cossacks II: Ba","GSC Game World",71));
        extend_table.add(Juego("4900","Zen of Sudoku","Unknown Worlds Entertainment",0));
        extend_table.add(Juego("4920","Natural Selecti","Unknown Worlds Entertainment",253));
        extend_table.add(Juego("6000","STAR WARS Repub","LucasArts",265));
        extend_table.add(Juego("6010","Indiana Jones a","LucasArts",804));
        extend_table.add(Juego("6020","STAR WARS Jedi ","Raven Software;Aspyr (Mac)",174));
        extend_table.add(Juego("6030","STAR WARS Jedi ","Raven Software;Aspyr (Mac)",180));
        extend_table.add(Juego("6040","The Dig","LucasArts",801));
        extend_table.add(Juego("6060","Star Wars: Batt","Pandemic Studios",320));
        extend_table.add(Juego("6080","Thrillville: Of","Frontier",17));
        extend_table.add(Juego("6090","Armed and Dange","Planet Moon Studios",100));
        extend_table.add(Juego("6120","Shank","Klei Entertainment",363));
        extend_table.add(Juego("6200","Ghost Master","Sick Puppies",21));
        extend_table.add(Juego("6210","Vegas: Make It ","Deepred",0));
        extend_table.add(Juego("6220","FlatOut","Bugbear Entertainment",96));
        extend_table.add(Juego("6250","Making History:","Muzzy Lane",0));
        extend_table.add(Juego("6270","Ducati World Ch","Artematica Entertainment",0));
        extend_table.add(Juego("6300","Dreamfall: The ","Funcom",20));
        extend_table.add(Juego("6310","The Longest Jou","Funcom",19));
        extend_table.add(Juego("6370","Bloodline Champ","Stunlock Studios",102));
        extend_table.add(Juego("6400","Joint Task Forc","Most Wanted Entertainment",0));
        extend_table.add(Juego("6420","Nexus - The Jup","Mithis Games;THQ Nordic",0));
        extend_table.add(Juego("6510","Lost Planet: Ex","CAPCOM Co., Ltd.",74));
        extend_table.add(Juego("6550","Devil May Cry 3","CAPCOM Co., Ltd.",90));
        extend_table.add(Juego("6800","Commandos: Behi","Pyro Studios",70));
        extend_table.add(Juego("6810","Commandos: Beyo","Pyro Studios",14));
        extend_table.add(Juego("6830","Commandos 2: Me","Pyro Studios",302));
        extend_table.add(Juego("6840","Commandos 3: De","Pyro Studios",20));
        extend_table.add(Juego("6850","Hitman 2: Silen","Io-Interactive A/S",58));
        extend_table.add(Juego("6860","Hitman: Blood M","Io-Interactive A/S",365));
        extend_table.add(Juego("6870","Battlestations:","Eidos Interactive",0));
        extend_table.add(Juego("6880","Just Cause","Avalanche Studios",25));
        extend_table.add(Juego("6900","Hitman: Codenam","IO Interactive A/S",43));
        extend_table.add(Juego("6910","Deus Ex: Game o","Ion Storm",245));
        extend_table.add(Juego("6920","Deus Ex: Invisi","Ion Storm",31));
        extend_table.add(Juego("6980","Thief: Deadly S","Ion Storm",368));
        extend_table.add(Juego("7000","Tomb Raider: Le","Crystal Dynamics",725));
        extend_table.add(Juego("7010","Project: Snowbl","Crystal Dynamics",0));
        extend_table.add(Juego("7020","Rogue Trooper","Rebellion",0));
        extend_table.add(Juego("7110","Jade Empire: Sp","BioWare Corporation",0));
        extend_table.add(Juego("7200","Trackmania Unit","Nadeo",4774));
        extend_table.add(Juego("7210","Runaway, A Road","Pendulo Studios",14));
        extend_table.add(Juego("7220","Runaway, The Dr","Pendulo Studios",0));
        extend_table.add(Juego("7260","Loki","Cyanide Studios",0));
        extend_table.add(Juego("7340","Azada","Big Fish Games",0));
        extend_table.add(Juego("7510","X-Blades","Gaijin Entertainment",341));
        extend_table.add(Juego("7520","Two Worlds II H","Reality Pump Studios",403));
        extend_table.add(Juego("7530","Two Worlds II C","Reality Pump Studios",330));
        extend_table.add(Juego("7600","Sid Meier's Rai","Firaxis Games;Feral Interactive (Mac)",253));
        extend_table.add(Juego("7610","Railroad Tycoon","PopTop",46));
        extend_table.add(Juego("7620","Railroad Tycoon","PopTop",1261));
        extend_table.add(Juego("7650","X-COM: Terror F","MicroProse Software, Inc",82));
        extend_table.add(Juego("7660","X-COM: Apocalyp","MicroProse Software, Inc",18));
        extend_table.add(Juego("7730","X-COM: Intercep","MicroProse Software, Inc",0));
        extend_table.add(Juego("7760","X-COM: UFO Defe","MicroProse Software, Inc",2224));
        extend_table.add(Juego("7770","X-COM: Enforcer","MicroProse Software, Inc",0));
        extend_table.add(Juego("7830","Men of War","Best Way",0));
        extend_table.add(Juego("7840","Death Track: Re","Sky Fallen",0));
        extend_table.add(Juego("7860","NecroVision","The Farm 51",113));
        extend_table.add(Juego("7940","Call of Duty 4:","Infinity Ward;Aspyr (Mac)",1503));
        extend_table.add(Juego("8000","Tomb Raider: An","Crystal Dynamics;Feral Interactive (Mac)",280));
        extend_table.add(Juego("8080","Kane and Lynch:","IO Interactive",209));
        extend_table.add(Juego("8100","Conflict: Denie","Pivotal Games",0));
        extend_table.add(Juego("8140","Tomb Raider: Un","Crystal Dynamics",565));
        extend_table.add(Juego("8170","Battlestations ","Eidos Studio Hungary",132));
        extend_table.add(Juego("8190","Just Cause 2","Avalanche Studios",272));
        extend_table.add(Juego("8310","Bone: Out From ","Telltale Games",0));
        extend_table.add(Juego("8320","Bone: The Great","Telltale Games",0));
        extend_table.add(Juego("8330","Telltale Texas ","Telltale Games",0));
        extend_table.add(Juego("8340","Strong Bad's Co","Telltale Games",0));
        extend_table.add(Juego("8400","Geometry Wars: ","Bizarre Creations",109));
        extend_table.add(Juego("8500","EVE Online","CCP",230));
        extend_table.add(Juego("8600","RACE 07","SimBin",218));
        extend_table.add(Juego("8790","GTR 2 FIA GT Ra","SimBin Studios AB",0));
        extend_table.add(Juego("8800","Civilization IV","Firaxis Games",108));
        extend_table.add(Juego("8870","BioShock Infini","Irrational Games;Aspyr (Mac);Virtual Programming (Linux)",519));
        extend_table.add(Juego("8880","Freedom Force","Irrational Games",16));
        extend_table.add(Juego("8890","Freedom Force v","Irrational Games",23));
        extend_table.add(Juego("8930","Sid Meier's Civ","Firaxis Games;Aspyr (Mac);Aspyr (Linux)",1797));
        extend_table.add(Juego("8970","Axel & Pixel","Silver Wish Games",0));
        extend_table.add(Juego("9000","Spear of Destin","id Software",0));
        extend_table.add(Juego("9010","Return to Castl","Gray Matter Studios",48));
        extend_table.add(Juego("9030","QUAKE Mission P","Rogue Entertainment",91));
        extend_table.add(Juego("9040","QUAKE Mission P","Ritual Entertainment",152));
        extend_table.add(Juego("9050","DOOM 3","id Software",394));
        extend_table.add(Juego("9060","HeXen II","Raven Software",10));
        extend_table.add(Juego("9160","Master Levels f","id Software",12));
        extend_table.add(Juego("9180","Commander Keen","id Software",145));
        extend_table.add(Juego("9200","RAGE","id Software",392));
        extend_table.add(Juego("9310","Warhammer 40,00","Relic Entertainment",365));
        extend_table.add(Juego("9340","Company of Hero","Relic Entertainment",106));
        extend_table.add(Juego("9350","Supreme Command","Gas Powered Games",306));
        extend_table.add(Juego("9420","Supreme Command","Gas Powered Games",1067));
        extend_table.add(Juego("9450","Warhammer 40,00","Relic Entertainment",1629));
        extend_table.add(Juego("9460","Frontlines: Fue","Kaos Studios",154));
        extend_table.add(Juego("9480","Saints Row 2","Volition",81));
        extend_table.add(Juego("9500","Gish","Cryptic Sea",23));
        extend_table.add(Juego("9710","Desperados 2: C","Spellbound",0));
        extend_table.add(Juego("9760","Act of War: Hig","Eugen Systems",0));
        extend_table.add(Juego("9800","Death to Spies","Haggard Games",84));
        extend_table.add(Juego("9850","Codename: Panze","InnoGlow;Stormregion;THQ Nordic",0));
        extend_table.add(Juego("9880","Champions Onlin","Cryptic Studios",724));
        extend_table.add(Juego("9900","Star Trek Onlin","Cryptic Studios",638));
        extend_table.add(Juego("9940","Blade Kitten","Krome Studios",360));
        extend_table.add(Juego("9960","Haunted House","ImagineEngline",0));
        extend_table.add(Juego("9970","Star Raiders","Incinerator Studios",0));
        extend_table.add(Juego("9980","The UnderGarden","Artech Studios",23));
        extend_table.add(Juego("10090","Call of Duty: W","Treyarch",1108));
        extend_table.add(Juego("10100","King's Quest Co","Sierra",19));
        extend_table.add(Juego("10110","Space Quest Col","Sierra",10));
        extend_table.add(Juego("10120","Aces of the Gal","Artech Studios",0));
        extend_table.add(Juego("10130","TimeShift","Saber Interactive",0));
        extend_table.add(Juego("10140","3D Ultra Minigo","Wanako Games",0));
        extend_table.add(Juego("10150","Prototype","Radical Entertainment",1001));
        extend_table.add(Juego("10180","Call of Duty: M","Infinity Ward;Aspyr (Mac)",580));
        extend_table.add(Juego("10220","Postal III","Trashmasters",411));
        extend_table.add(Juego("10230","Dead Mountainee","Electronic Paradise",0));
        extend_table.add(Juego("10240","A Stroke of Fat","SPLine",0));

    }
};


#endif //GG_PSQL_BD2_TESTEXTENDIBLE_H
